[package]
name = "anLocales"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
chrono = "0.4.42"
serde_json = "1.0.145"
toml = "0.9.7"
