name: Build anLocales

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build Library on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build on Linux/macOS
        if: matrix.os != 'windows-latest'
        run: make
        shell: bash

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        run: |
          make build
          mkdir dist
          Copy-Item target\release\anLocales.dll dist
          Copy-Item header\anlocales.h dist
        shell: pwsh

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: anlocales-${{ matrix.os }}
          path: dist/
