name: Publish Rust crate

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[0].version')
          echo "Current version: $VERSION"
          
          cargo publish --no-verify || true
          echo "Publish step finished (version may already exist)"
