name: Publish Rust crate

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Get crate version
        id: version
        run: |
          VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[0].version')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Publish if new version
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[0].version')
          echo "Current version: $VERSION"
          
          EXISTS=$(curl -s https://crates.io/api/v1/crates/anLocales | jq -r ".versions[]?.num" | grep -x "$VERSION" || true)
          
          if [ -z "$EXISTS" ]; then
            echo "Version $VERSION not found, publishing..."
            cargo publish --no-verify
          else
            echo "Version $VERSION already exists on crates.io, skipping publish"
          fi
