name: Publish Rust crate

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Get crate version
        id: version
        run: |
          VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[0].version')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Publish if new version
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[0].version')
          echo "Current version: $VERSION"
          
          if cargo search anLocales | grep -q "^anLocales = \"$VERSION\""; then
            echo "Version exists, skipping"
          else
            cargo publish --no-verify
          fi
